import RambaghPalace from "./images/RambaghPalace.jpg";
import OzenReserve from "./images/OzenReserve.jpg";
import HotelCollinedeFrance from "./images/HotelCollinedeFrance.jpg";
import ShangriLaTheShard from "./images/ShangriLaTheShard.jpg";
import theritzcarltonhongkong from "./images/theritzcarltonhongkong.jpg";
import NovotelAhmedabadHotel from "./images/NovotelAhmedabadHotel.jpg";
import TheRoyalSurakartaHeritage from "./images/TheRoyalSurakartaHeritage.jpg";
import GrandMercure from "./images/GrandMercure.jpg";
import hotelickale from "./images/hotelickale.jpg";
import GrandVenusLaResidence from "./images/GrandVenusLaResidence.jpg";
import AnantaraAngkorResort from "./images/AnantaraAngkorResort.jpg";
import Mementos from "./images/Mementos.jpg";
import HuaHin from "./images/HuaHin.jpg";
import dusitprincessmoonrise from "./images/dusitprincessmoonrise.jpg";
import sooribali from "./images/sooribali.jpg";
import theGreatBarrierReef from "./images/theGreatBarrierReef.jpg";
import TajWellingtonMews from "./images/TajWellingtonMews.jpeg";
import TheRadisonBlue from "./images/TheRadisonBlue.jpg";
import peninsula from "./images/peninsula.jpg";
import thesofia from "./images/thesofia.jpg";

const hotelsData = [
  {
    id: 1,
    name: "Rambagh Palace",
    category: "Luxury Hotels",
    city: "Jaipur",
    country: "India",
    rating: 5,
    price: 250,
    imgSrc: RambaghPalace,
    facilities: ["Swimming Pool", "Gym", "Spa", "Restaurant"],
  },
  {
    id: 2,
    name: "The Royal Surakarta Heritage",
    category: "Budget Friendly",
    city: "Surakarta",
    country: "Indonesia",
    rating: 3.8,
    price: 120,
    imgSrc: TheRoyalSurakartaHeritage,
    facilities: ["Wi-Fi", "Restaurant"],
  },
  {
    id: 3,
    name: "Anantara Angkor Resort",
    category: "Resort",
    city: "Siem Reap",
    country: "Cambodia",
    rating: 4.7,
    price: 300,
    imgSrc: AnantaraAngkorResort,
    facilities: ["Spa", "Restaurant", "Bar", "Swimming Pool"],
  },
  {
    id: 4,
    name: "Mementos by ITC Hotels",
    category: "Resort",
    city: "Udaipur",
    country: "India",
    rating: 4.7,
    price: 300,
    imgSrc: Mementos,
    facilities: ["Swimming Pool", "Gym", "Spa", "Restaurant"],
  },
  {
    id: 5,
    name: "Hilton Hua Hin Resort & Spa",
    category: "Beachfront",
    city: "Hua Hin",
    country: "Thailand",
    rating: 4.7,
    price: 300,
    imgSrc: HuaHin,
    facilities: ["Wi-Fi", "Restaurant"],
  },
  {
    id: 6,
    name: "Ozen Reserve",
    category: "Luxury Hotels",
    city: "Bolifushi Island",
    country: "Maldives",
    rating: 4.7,
    price: 300,
    imgSrc: OzenReserve,
    facilities: ["Wi-Fi", "Restaurant"],
  },
  {
    id: 7,
    name: "Novotel Ahmedabad Hotel",
    category: "Budget Friendly",
    city: "Ahmedabad",
    country: "India",
    rating: 4.7,
    price: 300,
    imgSrc: NovotelAhmedabadHotel,
    facilities: ["Swimming Pool", "Gym", "Spa", "Restaurant"],
  },
  {
    id: 8,
    name: "Taj Wellington Mews",
    category: "Business Purpose",
    city: "Mumbai",
    country: "India",
    rating: 4.7,
    price: 300,
    imgSrc: TajWellingtonMews,
    facilities: ["Wi-Fi", "Restaurant"],
  },
  {
    id: 9,
    name: "Grand Mercure Maha Cipta Medan Angkasa",
    category: "Budget Friendly",
    city: "Medan",
    country: "Indonesia",
    rating: 4.7,
    price: 300,
    imgSrc: GrandMercure,
    facilities: ["Swimming Pool", "Gym", "Spa", "Restaurant"],
  },
  {
    id: 10,
    name: "Hotel Colline de France",
    category: "Luxury Hotels",
    city: "Gramado",
    country: "Brazil",
    rating: 4.7,
    price: 300,
    imgSrc: HotelCollinedeFrance,
    facilities: ["Wi-Fi", "Restaurant"],
  },
  {
    id: 11,
    name: " Shangri-La The Shard",
    category: "Luxury Hotels",
    city: "London",
    country: "United Kingdom",
    rating: 4.7,
    price: 300,
    imgSrc: ShangriLaTheShard,
    facilities: ["Swimming Pool", "Gym", "Spa", "Restaurant"],
  },
  {
    id: 12,
    name: "The Peninsula ",
    category: "Business Purpose",
    city: "Hong Kong",
    country: "Chaina",
    rating: 4.7,
    price: 300,
    imgSrc: peninsula,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 13,
    name: "The Ritz Carlton",
    category: "Luxury Hotels",
    city: "Hong Kong",
    country: "China",
    rating: 4.7,
    price: 300,
    imgSrc: theritzcarltonhongkong,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 14,
    name: "Dusit Princess Moonrise",
    category: "Beachfront",
    city: "Phu Quoc Island",
    country: "Vietnam",
    rating: 4.7,
    price: 300,
    imgSrc: dusitprincessmoonrise,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 15,
    name: "Hotel İçkale Ankara",
    category: "Budget Friendly",
    city: "Ankara",
    country: "Turkey",
    rating: 4.7,
    price: 300,
    imgSrc: hotelickale,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 16,
    name: "The Radisson Blu Hotel",
    category: "Business Purpose",
    city: "Manchester",
    country: "England",
    rating: 4.7,
    price: 300,
    imgSrc: TheRadisonBlue,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 17,
    name: "The Sofia Hotel",
    category: "Business Purpose",
    city: "San Diego",
    country: "United Country",
    rating: 4.7,
    price: 300,
    imgSrc: thesofia,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 18,
    name: "Soori Bali",
    category: "Beachfront",
    city: "Tabnan",
    country: "Indonesia",
    rating: 4.7,
    price: 300,
    imgSrc: sooribali,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 19,
    name: " Grand Venus La Residence",
    category: "Budget Friendly",
    city: "Siem Reap",
    country: "Cambodia",
    rating: 4.7,
    price: 300,
    imgSrc: GrandVenusLaResidence,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
  {
    id: 20,
    name: "The Great Barrier Reef",
    category: "Beachfront",
    city: "Hayman Island ",
    country: "Australia",
    rating: 4.7,
    price: 300,
    imgSrc: theGreatBarrierReef,
    facilities: ["Spa", "Restaurant", "Bar"],
  },
];

export default hotelsData;
